export const GET_BOOKS_START = "GET_BOOKS_START";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";

export const REMOVE_BOOK_START = "REMOVE_BOOK_START";
export const REMOVE_BOOK_SUCCESS = "REMOVE_BOOK_SUCCESS";
export const REMOVE_BOOK_FAILURE = "REMOVE_BOOK_FAILURE";
